name: 'Build and Deploy'

on:
  push:
    branches: master
    tags: '*'

jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            # overrides the file ~/.m2/settings.xml with data to publish to maven pkg server with id github
            overwrite-settings: true
        - name: Build
          run: mvn install --no-transfer-progress
        - name: Get current version
          id: version
          run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)"
        - run: echo ${{steps.version.outputs.prop}}
        - name: Create Release
          id: create_release
          uses: ncipollo/release-action@latest
          with:
            tag: v${{steps.version.outputs.prop}}
            commit: master
            artifacts: target/boot-properties-logger-starter-${{steps.version.outputs.prop}}.jar
            artifactContentType: application/java-archive
            generateReleaseNotes: true
