name: 'Build and Deploy'

permissions:
  packages: write

on:
  push:
    branches: master
    tags: '*'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            # overrides the file ~/.m2/settings.xml with data to publish to maven pkg server with id github
            overwrite-settings: true
        - name: Build
          run: mvn install --no-transfer-progress
        - name: Get current version
          id: version
          run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)"
        - run: echo ${{steps.version.outputs.prop}}
        - name: Create Release
          id: create_release
          uses: actions/create-release@latest
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{steps.version.outputs.prop}}
            release_name: Release ${{steps.version.outputs.prop}}
            draft: false
            prerelease: false
        - name: Upload Release Asset
          id: upload-release-asset 
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: target/boot-properties-logger-starter-${{steps.version.outputs.prop}}.jar
            asset_name: boot-properties-logger-starter.jar
            asset_content_type: application/java-archive
