name: 'Build and Deploy new releases'

on:
  push:
    tags: [ 'v[0-9]+.[0-9]+.[0-9]+' ]

jobs:
    BuildThenDeployRelease:
      runs-on: ubuntu-latest
      permissions:
        contents: write
      steps:
        - uses: actions/checkout@v4
        - name: Set up JDK
          uses: actions/setup-java@v4
          with:
            java-version: '17'
            distribution: 'temurin'
            cache: 'maven'
            server-id: central
            server-username: MAVEN_USERNAME
            server-password: MAVEN_CENTRAL_TOKEN
            # overrides the file ~/.m2/settings.xml with data to publish to maven pkg server with id github
            overwrite-settings: true
        - name: Build and Sign*
          env:
            MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
            MAVEN_GPG_KEY: ${{ secrets.MAVEN_GPG_KEY }}
            MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
            MAVEN_CENTRAL_TOKEN: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
          run: mvn install gpg:sign --no-transfer-progress
        - name: Get current version
          id: version
          run: echo "::set-output name=prop::$(mvn -f pom.xml help:evaluate -Dexpression=project.version -q -DforceStdout)"
        - run: echo ${{steps.version.outputs.prop}}
        - run: mv target/boot-properties-logger-starter-${{steps.version.outputs.prop}}.jar target/boot-properties-logger-starter.jar
        - name: Create Release
          id: create_release
          uses: ncipollo/release-action@v1.16.0
          with:
            tag: v${{steps.version.outputs.prop}}
            commit: master
            artifacts: target/boot-properties-logger-starter.jar
            artifactContentType: application/java-archive
            generateReleaseNotes: true
